### ISSUE TITLE
cmd/cueckoo: switch away from x/build

### ISSUE THREAD

**Issue by mvdan** [cue-sh/tools#22]
x/build provides a gerrit client package, but it has two problems:

1) It is fairly incomplete, only supporting the API endpoints and request/response fields that x/build itself needs. It is not a complete client meant for general use.

2) x/build has quite a few heavy dependencies - its go.mod has ~120 lines.

We can solve both of those by switching to https://github.com/andygrunwald/go-gerrit. As a bonus, that is what we use in the cuelang.org repo, for the part of the codebase that reacts to webhooks - such as when we post a comment on Gerrit CLs when a trybot run finishes.

cc @myitcv

**Comment by myitcv** [comment]
No objections here.
