### ISSUE TITLE
cmd/cueckoo: set upstream when importing from PR

### ISSUE THREAD

**Issue by myitcv** [cue-sh/tools#24]
When importing a PR that has a target branch of something other that the remote default, we need to set the upstream of the branch that holds the imported PR to be that target branch.

This is now pretty critical because we have an `alpha` branch for cuelang.org (and will have so for some time, before graduating to a `beta` branch). We will also have release branches in the main CUE project.

**Comment by mvdan** [comment]
Ack, will look at this as soon as I can.

**Comment by mvdan** [comment]
I also used https://github.com/cue-sh/tools/pull/25 and https://github.com/cue-sh/tools/pull/26 to test PRs against a custom branch and against the default branch, respectively.
